### ISSUE TITLE
Demo site seems to be broken

### ISSUE THREAD

**Issue by Kehet** [carlescliment/calendar-bundle#15]
[demo site](http://www.bonniechef.com/calendar) mentioned in README.md currently returns 404

**Comment by BonnieDoug** [comment]
Sorry that is my fault, currently in the process of reworking my server tidy it up a bit etc. I'll hopefully get it sorted tonight if not it'll be ready tomorrow.

**Comment by carlescliment** [comment]
Thanks Doug!

**Comment by yugnats** [comment]
Still down?

**Comment by carlescliment** [comment]
Seems so. I'm going to update the doc. Thanks for reporting, @yugnats.

**Comment by carlescliment** [comment]
Thanks for reporting, @Kehet
