### ISSUE TITLE
Customizing view

### ISSUE THREAD

**Issue by 8draco8** [carlescliment/calendar-bundle#19]
I am trying to customize template of calendar. I am doing everything as per documentation but when I am copying base.html.twig as per this https://github.com/carlescliment/calendar-bundle#1-override-the-default-base-template nothing happening. Bundle is still using templates from vendor directory and not from my bundle.

Am I doing something wrong?

**Comment by carlescliment** [comment]
Hi @8draco8, did you extend the CalendarBundle from your own?

```
   public function getParent()
    {
        return 'BladeTesterCalendarBundle';
    }
```

**Comment by 8draco8** [comment]
Yes I did but the solution was stupid simple ....  clear cache. After that everything worked. I had some problems with extending my base template but I solved that by putting every non-twig code in twig blocks.

**Comment by carlescliment** [comment]
good!
